services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
volumes:
  pgdata:
