# Generated by Django 5.2.1 on 2025-06-04 12:47

from django.db import migrations

from tasks.models import Task


def change_archived_tasks(apps, schema_editor):
    Task.objects.filter(status="ARCHIVED").update(status="DONE")


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(change_archived_tasks),
    ]
